const ProgressBarConstants = {
  SET_PROGRESS_VALUE: 'SET_PROGRESS_VALUE',
  ENABLE_INDETERMINATE_PROGRESS_BAR: 'ENABLE_INDETERMINATE_PROGRESS_BAR',
  DISABLE_INDETERMINATE_PROGRESS_BAR: 'DISABLE_INDETERMINATE_PROGRESS_BAR'
}

export default ProgressBarConstants