const AuthConstants = {
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  SET_MASTER_PASSWORD: 'SET_MASTER_PASSWORD',
  CLEAR_MASTER_PASSWORD: 'CLEAR_MASTER_PASSWORD',
  LOGOUT: 'LOGOUT'
}

export default AuthConstants