const GlobalConstants = {
  END_APP_LOADING: 'END_APP_LOADING',
  OPEN_NEW_ENTRY_DIALOG: 'OPEN_NEW_ENTRY_DIALOG',
  OPEN_NEW_CATEGORY_DIALOG: 'OPEN_NEW_CATEGORY_DIALOG',
  OPEN_MASTER_PASSWORD_DIALOG: 'OPEN_MASTER_PASSWORD_DIALOG',
  OPEN_USER_SETTINGS_DIALOG: 'OPEN_USER_SETTINGS_DIALOG',
  OPEN_SET_NEW_USER_DIALOG: 'OPEN_SET_NEW_USER_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG'
}

export default GlobalConstants
