export enum AlertStatus {
  success = 'success',
  info = 'info',
  warning = 'warning',
  error = 'error'
}

export const UIConstants = {
  END_APP_LOADING: 'END_APP_LOADING',
  ADD_ALERT: 'ADD_ALERT',
  OPEN_NEW_ENTRY_DIALOG: 'OPEN_NEW_ENTRY_DIALOG',
  OPEN_NEW_CATEGORY_DIALOG: 'OPEN_NEW_CATEGORY_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
  SET_PROGRESS_VALUE: 'SET_PROGRESS_VALUE',
  ENABLE_INDETERMINATE_PROGRESS_BAR: 'ENABLE_INDETERMINATE_PROGRESS_BAR',
  DISABLE_INDETERMINATE_PROGRESS_BAR: 'DISABLE_INDETERMINATE_PROGRESS_BAR'
}
