export const UserConstants = {
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_ERROR: 'GOOGLE_LOGIN_ERROR',
  MASTER_PASSWORD_SUCCESS: 'MASTER_PASSWORD_SUCCESS',
  MASTER_PASSWORD_ERROR: 'MASTER_PASSWORD_ERROR',
  CLEAR_MASTER_PASSWORD: 'CLEAR_MASTER_PASSWORD',
  CLEAR: 'LOGOUT'
};
