name: Build-and-Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16'
      - name: Setup Yarn Env
        run: yarn
      - name: Run unit tests
        run: yarn test:ci
      - name: Build app
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
    
        
