name: Build-and-Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16'
      - name: Setup Yarn Env
        run: yarn
      - shell: bash
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        run: |
          echo "REACT_APP_GOOGLE_API_KEY=\"$GOOGLE_API_KEY\"" > .env
          echo "REACT_APP_GOOGLE_CLIENT_ID=\"$GOOGLE_CLIENT_ID\"" >> .env
      - name: Run unit tests
        run: yarn test:ci
      - name: Build app
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
    
        
