name: Build-and-Test

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '16'
      - name: Setup Yarn Env
        run: yarn
      - name: Build
        run: yarn build
      - name: Unit Test
        run: yarn test:ci